# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 0 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 1 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 2 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 3 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 4 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 5 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 6 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 7 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 8 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question_Answer" --fold 9 --seed 2020 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4


# python training-k-fold.py --model_name "bert-base-uncased" --content "Question" --fold 0 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question" --fold 1 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question" --fold 2 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question" --fold 3 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4
# python training-k-fold.py --model_name "bert-base-uncased" --content "Question" --fold 4 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4


python training-k-fold.py --model_name "bert-base-uncased" --content "Answer" --fold 0 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4 --load_pretrain
python training-k-fold.py --model_name "bert-base-uncased" --content "Answer" --fold 1 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4 --load_pretrain
python training-k-fold.py --model_name "bert-base-uncased" --content "Answer" --fold 2 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4 --load_pretrain
python training-k-fold.py --model_name "bert-base-uncased" --content "Answer" --fold 3 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4 --load_pretrain
python training-k-fold.py --model_name "bert-base-uncased" --content "Answer" --fold 4 --seed 2020 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 1e-4 --loss "bce" --augment --num_epoch 13 --num_workers 4 --load_pretrain