# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question" --max_len 768 --fold 0 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question" --max_len 768 --fold 1 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question" --max_len 768 --fold 2 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question" --max_len 768 --fold 3 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question" --max_len 768 --fold 4 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain


# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Answer" --max_len 768 --fold 0 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Answer" --max_len 768 --fold 1 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Answer" --max_len 768 --fold 2 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Answer" --max_len 768 --fold 3 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Answer" --max_len 768 --fold 4 --seed 1997 --n_splits 5 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain


# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question_Answer" --max_len 768 --fold 0 --seed 777 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question_Answer" --max_len 768 --fold 1 --seed 777 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question_Answer" --max_len 768 --fold 2 --seed 777 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question_Answer" --max_len 768 --fold 3 --seed 777 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
# python swa-k-fold.py --model_type "xlnet" --model_name "xlnet-base-cased" --content "Question_Answer" --max_len 768 --fold 4 --seed 777 --n_splits 10 --batch_size 4 --valid_batch_size 32 --accumulation_steps 2 --lr 5e-7 --loss "bce" --augment --num_epoch 3 --num_workers 4 --load_pretrain
