python training-k-fold.py --model_name "t5-base" --content "Answer" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 0 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4 
# python training-k-fold.py --model_name "t5-base" --content "Answer" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 1 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4 
# python training-k-fold.py --model_name "t5-base" --content "Answer" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 2 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4 
# python training-k-fold.py --model_name "t5-base" --content "Answer" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 3 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4 
# python training-k-fold.py --model_name "t5-base" --content "Answer" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 4 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4 

# python training-k-fold.py --model_name "t5-base" --content "Question" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 0 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4
# python training-k-fold.py --model_name "t5-base" --content "Question" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 1 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4
# python training-k-fold.py --model_name "t5-base" --content "Question" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 2 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4
# python training-k-fold.py --model_name "t5-base" --content "Question" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 3 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4
# python training-k-fold.py --model_name "t5-base" --content "Question" --lr_scheduler "'CosineAnealing" --max_len 512 --fold 4 --seed 901 --n_splits 5 --split "GroupKfold" --batch_size 2 --valid_batch_size 32 --accumulation_steps 16 --lr 1e-3 --loss "bce" --augment --num_epoch 8 --num_workers 4

